ARIA Download NISAR GUNWs
aria-tools/ARIA-tools pull request #394
Opened 2024-04-09 17:57 UTC by bbuzz31

add download support for NISAR GUNWs

2024-04-10 10:06 UTC, alexfore requested changes
I added some questions and a few style points

2024-04-10 10:06 UTC, alexfore commented on tools/bin/ariaDownload.py
> +            print (scenes[0])
should this be logged instead of printed, other code in this block uses logger
`print (` should be `print(` (no whitespace before open parenthesis that starts the argument list of a function call)

2024-04-10 10:06 UTC, alexfore commented on tools/bin/ariaDownload.py
> +            LOGGER.info ('Token accepted.')
no whitespace before open parenthesis that starts the argument list of a function call

2024-04-10 10:06 UTC, alexfore commented on tools/bin/ariaDownload.py
> +            dct_kw = dict(dataset='ARIA S1 GUNW',
misalignment

2024-04-10 10:06 UTC, alexfore commented on tools/bin/ariaDownload.py
> +from dateutil.relativedelta import relativedelta
a comment on imports: In general, using the full path is more descriptive than taking parts of various packages as the namespace is truncated when using `from a import b`. IMO the full namespace is preferred due to the better descriptiveness but not always

2024-04-10 10:06 UTC, alexfore commented on tools/bin/ariaDownload.py
> +        st0 = self.args.start + relativedelta(months=-3)
can we rename this vars `start` and `end` to match the other naming of attributes of `args` and arguments to `asf_search.geo_search`

2024-04-10 10:06 UTC, alexfore commented on tools/bin/ariaDownload.py
> +            print (scenes[0])
Presumably the commented out lines will be uncommented later when other features are added? Can we add a TODO in the code here, is there some string we use in this repo to note features need to be added which is easy to search for

2024-04-10 10:06 UTC, alexfore commented on tools/bin/ariaDownload.py
> +        st0 = self.args.start + relativedelta(months=-3)
Is this a mistake here (why removing -3 months from both start and end)?

2024-04-10 16:25 UTC, bbuzz31 commented on tools/bin/ariaDownload.py
> +from dateutil.relativedelta import relativedelta
agreed, but I think this one is commonly used

2024-04-10 16:26 UTC, bbuzz31 commented on tools/bin/ariaDownload.py
> +            dct_kw = dict(dataset='ARIA S1 GUNW',
not sure what it's supposed to be

2024-04-10 17:18 UTC, alexfore commented on tools/bin/ariaDownload.py
> +            dct_kw = dict(dataset='ARIA S1 GUNW',
The llines are not aligned correctly

2024-04-10 17:19 UTC, alexfore commented on tools/bin/ariaDownload.py
> +            dct_kw = dict(dataset='ARIA S1 GUNW',
dct_kw = dict(dataset='ARIA S1 GUNW',
                        processingLevel=asf_search.constants.GUNW_STD,


dataset and processingLevel should be aligned on subsequent lines

2024-04-10 20:23 UTC, alexfore commented on tools/bin/ariaDownload.py
> +from dateutil.relativedelta import relativedelta
Recommend to use datetime.timedelta instead. We already use that in here. Also the pad should be a constant to avoid magic number anti pattern.

2024-04-11 11:35 UTC, alexfore commented
I've asked repeatedly for you to pay attention to the style of the code which you are committing. You have not done that so far. Please look at what you have done and ask yourself:
* Is what I have committed PEP8 compliant?
* Is the use of whitespace consistent with the rest of the code in this module?
* Is what I have committed improving the software or adding more issues that need to be fixed in the future?

I think that style is extremely important. From my point of view imposing style requirements on this code base is the first step to making it a maintainable code base. If the main developers on this project do not agree I will not be able to help

2024-04-11 13:11 UTC, bbuzz31 commented
I implemented all your requested changes. If you have more requests, point them out.

2024-04-11 17:54 UTC, jhkennedy commented
> I've asked repeatedly for you to pay attention to the style of the code which you are committing. You have not done that so far. Please look at what you have done and ask yourself:
> 
>     * Is what I have committed PEP8 compliant?
> 
>     * Is the use of whitespace consistent with the rest of the code in this module?
> 
>     * Is what I have committed improving the software or adding more issues that need to be fixed in the future? (technical debt)
> 
> 
> I think that style is extremely important. From my point of view imposing style requirements on this code base is the first step to making it a maintainable code base. If the main developers on this project do not agree I will not be able to help
> 
> It will be worth your time to memorize everything here: https://peps.python.org/pep-0008/


@alexfore, there seems to be a lot of unnecessary back and forth related to this that *should* be handled by CI/CD linting checks -- it's much better for everyone involved for a bot to be the arbiter. 

I suggest spending the effort on setting up a github action for flake8/pylint/ruff.

2024-04-12 13:25 UTC, alexfore commented
I would also love to integrate automated pep8 checks -- because I never want to have this conversation again. I do not like telling people that their code style is messy or inadequate, this clearly leads to conflict.

However, the fact remains that this PR has still contains pep8 violations -- whitespace and alignment.  My comments above still stand and I want to see them addressed before I will approve this PR. If someone is unwilling to improve I do not know what to say to that.  Maybe use pylint, pycodestyle, or flake8 and try to learn what the issues are. Me telling you or doing it myself is not going to help other people learn.

On my end I will figure out how to integrate the style checks I want in another PR.

2024-04-12 15:25 UTC, dbekaert commented
Hi @alexfore @jhkennedy I like the idea of a bot doing these sort of checks. I think they might even come with suggested fixes etc. Lets add that support in an upcoming PR and perhaps we can let the code-base run through it?

I would like to get the stable test suite in place, the dependency issue fixed for stability. With that in place we could route the code through the both for suggested changes?

2024-04-12 20:42 UTC, alexfore commented
I think we should close this PR. We can open it again once I've integrated pep8 auto checks into this repo, and / or the author has address these issues

2024-05-10 23:36 UTC, pep8speaks commented
Hello @bbuzz31! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`tools/bin/ariaDownload.py`](https://github.com/aria-tools/ARIA-tools/blob/8cfa1d02523accd76502cf9344e77b2cab958a0c/tools/bin/ariaDownload.py):

> [Line 36:80](https://github.com/aria-tools/ARIA-tools/blob/8cfa1d02523accd76502cf9344e77b2cab958a0c/tools/bin/ariaDownload.py#L36): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 37:22](https://github.com/aria-tools/ARIA-tools/blob/8cfa1d02523accd76502cf9344e77b2cab958a0c/tools/bin/ariaDownload.py#L37): [E131](https://duckduckgo.com/?q=pep8%20E131) continuation line unaligned for hanging indent
> [Line 41:80](https://github.com/aria-tools/ARIA-tools/blob/8cfa1d02523accd76502cf9344e77b2cab958a0c/tools/bin/ariaDownload.py#L41): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> [Line 318:9](https://github.com/aria-tools/ARIA-tools/blob/8cfa1d02523accd76502cf9344e77b2cab958a0c/tools/bin/ariaDownload.py#L318): [E266](https://duckduckgo.com/?q=pep8%20E266) too many leading '#' for block comment
> [Line 318:9](https://github.com/aria-tools/ARIA-tools/blob/8cfa1d02523accd76502cf9344e77b2cab958a0c/tools/bin/ariaDownload.py#L318): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 320:12](https://github.com/aria-tools/ARIA-tools/blob/8cfa1d02523accd76502cf9344e77b2cab958a0c/tools/bin/ariaDownload.py#L320): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator
> [Line 324:29](https://github.com/aria-tools/ARIA-tools/blob/8cfa1d02523accd76502cf9344e77b2cab958a0c/tools/bin/ariaDownload.py#L324): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 325:29](https://github.com/aria-tools/ARIA-tools/blob/8cfa1d02523accd76502cf9344e77b2cab958a0c/tools/bin/ariaDownload.py#L325): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 326:29](https://github.com/aria-tools/ARIA-tools/blob/8cfa1d02523accd76502cf9344e77b2cab958a0c/tools/bin/ariaDownload.py#L326): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 327:29](https://github.com/aria-tools/ARIA-tools/blob/8cfa1d02523accd76502cf9344e77b2cab958a0c/tools/bin/ariaDownload.py#L327): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 328:29](https://github.com/aria-tools/ARIA-tools/blob/8cfa1d02523accd76502cf9344e77b2cab958a0c/tools/bin/ariaDownload.py#L328): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 329:29](https://github.com/aria-tools/ARIA-tools/blob/8cfa1d02523accd76502cf9344e77b2cab958a0c/tools/bin/ariaDownload.py#L329): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 330:13](https://github.com/aria-tools/ARIA-tools/blob/8cfa1d02523accd76502cf9344e77b2cab958a0c/tools/bin/ariaDownload.py#L330): [E124](https://duckduckgo.com/?q=pep8%20E124) closing bracket does not match visual indentation
> [Line 331:29](https://github.com/aria-tools/ARIA-tools/blob/8cfa1d02523accd76502cf9344e77b2cab958a0c/tools/bin/ariaDownload.py#L331): [E116](https://duckduckgo.com/?q=pep8%20E116) unexpected indentation (comment)
> [Line 338:13](https://github.com/aria-tools/ARIA-tools/blob/8cfa1d02523accd76502cf9344e77b2cab958a0c/tools/bin/ariaDownload.py#L338): [E266](https://duckduckgo.com/?q=pep8%20E266) too many leading '#' for block comment
> [Line 341:29](https://github.com/aria-tools/ARIA-tools/blob/8cfa1d02523accd76502cf9344e77b2cab958a0c/tools/bin/ariaDownload.py#L341): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 349:25](https://github.com/aria-tools/ARIA-tools/blob/8cfa1d02523accd76502cf9344e77b2cab958a0c/tools/bin/ariaDownload.py#L349): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 351:27](https://github.com/aria-tools/ARIA-tools/blob/8cfa1d02523accd76502cf9344e77b2cab958a0c/tools/bin/ariaDownload.py#L351): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator

2024-05-11 12:00 UTC, alexfore commented
This PR needs to be abandoned. These code changes need to start from the dev branch after I've merged dev_refactor.

2024-05-11 12:00 UTC, closed without merging