No longer extract ancillary layers by default through ariaTSsetup
aria-tools/ARIA-tools pull request #418
Opened 2024-05-22 01:23 UTC by sssangha

Following convo with @mgovorcin and @dbekaert , adjust behavior of `ariaTSsetup.py` to no longer extract ancillary layers (i.e. 'solidEarthTide,ionosphere,troposphereTotal') by default. They now have to be explicitly specified in the commandline.

To test out these changes, refer to the following minimum working example:
1. Download a subset of version 3 products over southern California: `ariaDownload.py --num_threads 16 -b '33.4 34.5 -119.0 -117.4'  -s 20190101  -e 20190216 -t 64 --version 3_0_1 -o Download`

2. Test out default behavior of `ariaTSsetup.py` (i.e. layers 'solidEarthTide,ionosphere,troposphereTotal' should be missing from the specified output directory `-w ts_default`): `ariaTSsetup.py -f "products/*.nc" -b '33.6 34.3 -118.5 -117.5' -mo 5800 --verbose -of ENVI -w ts_output --log-level debug`

3. Explicitly specify extraction of ancillary layers (i.e. layers 'solidEarthTide,ionosphere,troposphereTotal' should be found in specified output directory `-w ts_output_ancillarylyrs`): ariaTSsetup.py -f "products/*.nc" -b '33.6 34.3 -118.5 -117.5' -mo 5800 --verbose -l 'solidEarthTide,ionosphere,troposphereTotal' -tm HRRR -of ENVI -w ts_output_ancillarylyrs --log-level debug

Note the `-mo 5800` should be specified here to reject short IFGs that do not meet the defined spatial threshold of coverage (i.e. 5800 km^2) WRT to the specified bbox. See a relevant discussion on this [here](https://github.com/aria-tools/ARIA-tools/issues/416).

2024-05-24 15:29 UTC, dbekaert commented
Given the logic changes i would suggest a few additional tests @sssangha:
1)  Test this for a mixed set of products forcing it not to extract layers.
2) Test this for mixed set of product and forcing to extract the layers (even though they dont exist..).

2024-05-24 15:35 UTC, mgovorcin approved these changes
Looks  good, thanks SIm

2024-05-28 12:03 UTC, alexfore requested changes
Hi @sssangha  -- the code changes look good to me. However, two of the tests in `tests/regression` do not pass anymore due to changes in which layers are extracted.

The download and extract cases pass while the tssetup and nisar extract cases do not pass due to lack of the `troposphereTotal` layer with this branch.

For nisar_extract:
If I add `-tm HRRR` to the ariaExtract.py command line args I see a logger message like this:
```
2024-05-28 04:59:57,399 - ARIAtools.util.vrt - WARNING - User-requested tropo model HRRR will not be generated as it does not exist in any of the input products
```

For tssetup:
If I add `-l "troposphereTotal" -tm HRRR ` to the command-line args I get an error like this:
```
raceback (most recent call last):
  File "/u/frode-z/fore/aria/miniforge/envs/ARIA-tools/bin/ariaTSsetup.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/u/frode-z/fore/aria/ARIA-tools/tools/bin/ariaTSsetup.py", line 632, in <module>
    main()
  File "/u/frode-z/fore/aria/ARIA-tools/tools/bin/ariaTSsetup.py", line 569, in main
    ARIAtools.util.vrt.dim_check(ref_arr_record, prod_arr_record)
  File "/u/frode-z/fore/aria/ARIA-tools/tools/ARIAtools/util/vrt.py", line 542, in dim_check
    raise Exception(
Exception: Inconsistent product dims between products test_outputs/tssetup/unwrappedPhase/20230829_20230724 and None: check respective width (4545, None) and height (3586, None) and geotrans ((-123.156617404, 0.000833332999999999, -0.0, 43.210816049, -0.0, -0.000833332999999999), None)
2024-05-28 05:02:45,600 - run_tssetup_test.py - ERROR - ariaTSsetup failed!
Traceback (most recent call last):
  File "/u/frode-z/fore/aria/ARIA-tools/tests/regression/./run_tssetup_test.py", line 66, in <module>
    main()
  File "/u/frode-z/fore/aria/ARIA-tools/tests/regression/./run_tssetup_test.py", line 62, in main
    run_subproc(exec_string, 'ariaTSsetup', raise_exception=True)
  File "/u/frode-z/fore/aria/ARIA-tools/tests/regression/./run_tssetup_test.py", line 41, in run_subproc
    raise Exception('%s failed!' % message)
Exception: ariaTSsetup failed!
```
So I'm unclear on how to resolve this, or if the golden test data should be updated

2024-05-28 21:40 UTC, sssangha commented
@alexfore thanks for your input and helping me track down an issue.

Looks like the logic I had in the code did not appropriately account for NISAR GUNW products when trying to extract tropo layers (which don't have denoted model names in their paths like their S1 GUNW counterparts do). I made a tweak to account for this, let me know if you advise I adjust it for clarity.

And yes, this PR would lead to changes in the golden outputs as the expected behavior changes. Let me please regenerate them, adjust the coordination doc to reflect these changes, + LFT the products to you

2024-05-28 22:10 UTC, sssangha commented
> Given the logic changes i would suggest a few additional tests @sssangha:
> 
>     1. Test this for a mixed set of products forcing it not to extract layers.
> 
>     2. Test this for mixed set of product and forcing to extract the layers (even though they dont exist..).

Let me add this to the golden 

> Given the logic changes i would suggest a few additional tests @sssangha:
> 
>     1. Test this for a mixed set of products forcing it not to extract layers.
> 
>     2. Test this for mixed set of product and forcing to extract the layers (even though they dont exist..).

Ok, @dbekaert I have a test that addresses this.

Download a mix of v2 and v3 products:
```
ariaDownload.py -t 137 --bbox '40.8 42.3 -122 -120' -i 20210330_20200329 -o Download
ariaDownload.py -t 137 --bbox '40.8 42.3 -122 -120' -i 20220331_20220319 -o Download
ariaDownload.py -t 137 --bbox '40.8 42.3 -122 -120' -i 20230829_20230724 -o Download
ariaDownload.py -t 137 --bbox '40.8 42.3 -122 -120' -i 20230829_20230817 -o Download
```

1. Test this for a mixed set of products forcing it not to extract layers:
`ariaTSsetup.py -f "products/*.nc" --verbose -of ENVI -w ts_output --log-level debug`

As expected, no ancillary layers are extracted by default (even when present for the v3 products:
```
ls ts_output
azimuthAngle  bPerpendicular  coherence  connectedComponents  DEM  export_workers  full_product_dict.json  incidenceAngle  lookAngle  productBoundingBox  stack  unwrappedPhase  user_bbox.json
```


2. Test this for mixed set of product and forcing to extract the layers (even though they dont exist..):
`ariaTSsetup.py -f "products/*.nc" --verbose -of ENVI -l 'solidEarthTide,ionosphere,troposphereTotal' -tm HRRR -w ts_output_ancillarylyrs --log-level debug`

Here is a list of all of the output layers:
```
ls ts_output_ancillarylyrs
azimuthAngle  bPerpendicular  coherence  connectedComponents  DEM  export_workers  full_product_dict.json  incidenceAngle  ionosphere  lookAngle  productBoundingBox  solidEarthTide  stack  troposphereTotal  unwrappedPhase  user_bbox.json
```

The ancillary layers are extracted ONLY for the v3 pairs.
Compare the unw phase vs tropo outputs:
```
ls ts_output_ancillarylyrs/unwrappedPhase/
20210330_20200329          20210330_20200329.hdr  20220331_20220319          20220331_20220319.hdr  20230829_20230724          20230829_20230724.hdr  20230829_20230817          20230829_20230817.hdr
20210330_20200329.aux.xml  20210330_20200329.vrt  20220331_20220319.aux.xml  20220331_20220319.vrt  20230829_20230724.aux.xml  20230829_20230724.vrt  20230829_20230817.aux.xml  20230829_20230817.vrt
```

```
ls ts_output_ancillarylyrs/troposphereTotal/HRRR/
20220331_20220319          20220331_20220319.hdr  20230829_20230724          20230829_20230724.hdr  20230829_20230817          20230829_20230817.hdr  dates
20220331_20220319.aux.xml  20220331_20220319.vrt  20230829_20230724.aux.xml  20230829_20230724.vrt  20230829_20230817.aux.xml  20230829_20230817.vrt
```



And not for the v2 pair (`*20210330_20200329*`):
```
ls products/*20210330_20200329*
products/S1-GUNW-A-R-137-tops-20210330_20200329-015957-41895N_400275N-PP-1ce2-v2_0_4.nc  products/S1-GUNW-A-R-137-tops-20210330_20200329-020019-43055N_41517N-PP-8010-v2_0_4.nc
```

2024-05-29 16:25 UTC, alexfore commented
Using that code change then I modified the `tests/regression/run_tssetup_test.py` tssetup run script to extract those layers again. Now all of the tests pass so these code changes could be merged. However, the next issue seems to be that you guys want to add more test cases / or replace the current tssetup test case?

2024-05-29 16:35 UTC, alexfore commented
Regarding the golden test data which was sent via LFT:
* The products in this are not the same as those which are obtained if I use the four ariaDownload.py commands above. Is this intentional or an oversight? (13 versus 2 netcdf files). Both of the products which were included in the golden test data via LFT are v3_0_0 files.

* Can we replace the previous tssetup case with one of these cases?

2024-05-29 17:25 UTC, sssangha commented
> Using that code change then I modified the `tests/regression/run_tssetup_test.py` tssetup run script to extract those layers again. Now all of the tests pass so these code changes could be merged. However, the next issue seems to be that you guys want to add more test cases / or replace the current tssetup test case?

What you did to the `run_tssetup_test.py` suffices. I don't think we should add another test case. Apologies for the confusion.

2024-05-29 17:28 UTC, sssangha commented
> Regarding the golden test data which was sent via LFT:
> 
>     * The products in this are not the same as those which are obtained if I use the four ariaDownload.py commands above. Is this intentional or an oversight? (13 versus 2 netcdf files). Both of the products which were included in the golden test data via LFT are v3_0_0 files.
> 
>     * Can we replace the previous tssetup case with one of these cases?

No, those 4 ariaDownload cases are unrelated to the golden outputs and shouldn't be reflected in the golden outputs. Whatever I shared in that comment was meant to address the questions @dbekaert raised. I think we could proceed as is. Thanks again @alexfore !

2024-05-29 17:47 UTC, alexfore approved these changes

2024-05-29 21:40 UTC, merged